# Syntax= docker/dockerfile:1

FROM node:20-alpine AS deps
WORKDIR /src
COPY backend/package.json backend/package-lock.json ./
RUN npm ci --omit=dev

FROM node:20-alpine AS runtime
WORKDIR /src
ENV NODE_ENV=production
COPY --from=deps /src/node_modules ./node_modules
COPY backend/ .
EXPOSE 3007
CMD ["node", "src/server.js"]
