# Syntax= docker/dockerfile:1

# ---------- 1. Build do Flutter Web ----------
FROM ghcr.io/gmeligio/flutter-web:3.47.2 AS build-web

USER root
RUN git config --global --add safe.directory /home/flutter/sdks/flutter

WORKDIR /src/app

COPY app/pubspec.yaml app/pubspec.lock* ./
RUN flutter pub get

COPY app/ .
RUN chown -R flutter:flutter /src/app

USER flutter
RUN flutter build web --release --dart-define=API_URL=/api

# ---------- 2. Servidor web (Nginx) ----------
FROM nginx:alpine AS web

# Remove a página default e copia o build
RUN rm -rf /usr/share/nginx/html/* && \
    rm -f /etc/nginx/conf.d/default.conf

COPY --from=build-web /src/app/build/web/ /usr/share/nginx/html/

# Configuração com proxy reverso para a API
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
